name = "MCParticles"
uuid = "24600035-b1cd-4d3f-b79a-9b7e18b664a2"
authors = ["Joshua Bon <joshuajbon@gmail.com>"]
version = "0.1.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
StatsFuns = "4c63d2b9-4356-54db-8cca-17b64c39e42c"

[compat]
Distributions = "0.23"
StatsFuns = "0.9"
julia = "1.4.2"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
